//
//  Country.swift
//  VisionaryTour
//
//  Created by JinNash on 2024/05/05.
//

enum Region: String {
    case asia = "Asia"
    case europe = "Europe"
    case africa = "Africa"
    case northAmerica = "NorthAmerica"
    case southAmerica = "SouthAmerica"
    case oceania = "Oceania"
    case others = "Others"
}

enum Country: String, CaseIterable {
    case afghanistan = "Afghanistan"
    case albania = "Albania"
    case algeria = "Algeria"
    case andorra = "Andorra"
    case angola = "Angola"
    case antiguaAndBarbuda = "Antigua and Barbuda"
    case argentina = "Argentina"
    case armenia = "Armenia"
    case australia = "Australia"
    case austria = "Austria"
    case azerbaijan = "Azerbaijan"
    case bahamas = "Bahamas"
    case bahrain = "Bahrain"
    case bangladesh = "Bangladesh"
    case barbados = "Barbados"
    case belarus = "Belarus"
    case belgium = "Belgium"
    case belize = "Belize"
    case benin = "Benin"
    case bhutan = "Bhutan"
    case bolivia = "Bolivia"
    case bosniaAndHerzegovina = "Bosnia and Herzegovina"
    case botswana = "Botswana"
    case brazil = "Brazil"
    case brunei = "Brunei"
    case bulgaria = "Bulgaria"
    case burkinaFaso = "Burkina Faso"
    case burundi = "Burundi"
    case cabVerde = "Cabo Verde"
    case cambodia = "Cambodia"
    case cameroon = "Cameroon"
    case canada = "Canada"
    case centralAfricanRepublic = "Central African Republic"
    case chad = "Chad"
    case chile = "Chile"
    case china = "China"
    case colombia = "Colombia"
    case comoros = "Comoros"
    case congo = "Congo"
    case costaRica = "Costa Rica"
    case coteDIvoire = "Côte d'Ivoire"
    case croatia = "Croatia"
    case cuba = "Cuba"
    case cyprus = "Cyprus"
    case czechia = "Czechia"
    case democraticRepublicOfTheCongo = "Democratic Republic of the Congo"
    case denmark = "Denmark"
    case djibouti = "Djibouti"
    case dominica = "Dominica"
    case dominicanRepublic = "Dominican Republic"
    case ecuador = "Ecuador"
    case egypt = "Egypt"
    case elSalvador = "El Salvador"
    case equatorialGuinea = "Equatorial Guinea"
    case eritrea = "Eritrea"
    case estonia = "Estonia"
    case eswatini = "Eswatini"
    case ethiopia = "Ethiopia"
    case fiji = "Fiji"
    case finland = "Finland"
    case france = "France"
    case gabon = "Gabon"
    case gambia = "Gambia"
    case georgia = "Georgia"
    case germany = "Germany"
    case ghana = "Ghana"
    case greece = "Greece"
    case grenada = "Grenada"
    case guatemala = "Guatemala"
    case guinea = "Guinea"
    case guineaBissau = "Guinea-Bissau"
    case guyana = "Guyana"
    case haiti = "Haiti"
    case honduras = "Honduras"
    case hungary = "Hungary"
    case iceland = "Iceland"
    case india = "India"
    case indonesia = "Indonesia"
    case iran = "Iran"
    case iraq = "Iraq"
    case ireland = "Ireland"
    case israel = "Israel"
    case italy = "Italy"
    case jamaica = "Jamaica"
    case japan = "Japan"
    case jordan = "Jordan"
    case kazakhstan = "Kazakhstan"
    case kenya = "Kenya"
    case kiribati = "Kiribati"
    case kuwait = "Kuwait"
    case kyrgyzstan = "Kyrgyzstan"
    case laos = "Laos"
    case latvia = "Latvia"
    case lebanon = "Lebanon"
    case lesotho = "Lesotho"
    case liberia = "Liberia"
    case libya = "Libya"
    case liechtenstein = "Liechtenstein"
    case lithuania = "Lithuania"
    case luxembourg = "Luxembourg"
    case madagascar = "Madagascar"
    case malawi = "Malawi"
    case malaysia = "Malaysia"
    case maldives = "Maldives"
    case mali = "Mali"
    case malta = "Malta"
    case marshallIslands = "Marshall Islands"
    case mauritania = "Mauritania"
    case mauritius = "Mauritius"
    case mexico = "Mexico"
    case micronesia = "Micronesia"
    case moldova = "Moldova"
    case monaco = "Monaco"
    case mongolia = "Mongolia"
    case montenegro = "Montenegro"
    case morocco = "Morocco"
    case mozambique = "Mozambique"
    case myanmar = "Myanmar"
    case namibia = "Namibia"
    case nauru = "Nauru"
    case nepal = "Nepal"
    case netherlands = "Netherlands"
    case newZealand = "New Zealand"
    case nicaragua = "Nicaragua"
    case niger = "Niger"
    case nigeria = "Nigeria"
    case northKorea = "North Korea"
    case northMacedonia = "North Macedonia"
    case norway = "Norway"
    case oman = "Oman"
    case pakistan = "Pakistan"
    case palau = "Palau"
    case panama = "Panama"
    case papuaNewGuinea = "Papua New Guinea"
    case paraguay = "Paraguay"
    case peru = "Peru"
    case philippines = "Philippines"
    case poland = "Poland"
    case portugal = "Portugal"
    case qatar = "Qatar"
    case romania = "Romania"
    case russia = "Russia"
    case rwanda = "Rwanda"
    case saintKittsAndNevis = "Saint Kitts and Nevis"
    case saintLucia = "Saint Lucia"
    case saintVincentAndTheGrenadines = "Saint Vincent and the Grenadines"
    case samoa = "Samoa"
    case sanMarino = "San Marino"
    case saoTomeAndPrincipe = "Sao Tome and Principe"
    case saudiArabia = "Saudi Arabia"
    case senegal = "Senegal"
    case serbia = "Serbia"
    case seychelles = "Seychelles"
    case sierraLeone = "Sierra Leone"
    case singapore = "Singapore"
    case slovakia = "Slovakia"
    case slovenia = "Slovenia"
    case solomonIslands = "Solomon Islands"
    case somalia = "Somalia"
    case southAfrica = "South Africa"
    case southKorea = "South Korea"
    case southSudan = "South Sudan"
    case spain = "Spain"
    case sriLanka = "Sri Lanka"
    case sudan = "Sudan"
    case suriname = "Suriname"
    case sweden = "Sweden"
    case switzerland = "Switzerland"
    case syria = "Syria"
    case tajikistan = "Tajikistan"
    case tanzania = "Tanzania"
    case thailand = "Thailand"
    case timorLeste = "Timor-Leste"
    case togo = "Togo"
    case tonga = "Tonga"
    case trinidadAndTobago = "Trinidad and Tobago"
    case tunisia = "Tunisia"
    case turkey = "Turkey"
    case turkmenistan = "Turkmenistan"
    case tuvalu = "Tuvalu"
    case uganda = "Uganda"
    case ukraine = "Ukraine"
    case uae = "UAE"
    case uk = "United Kingdom"
    case us = "United States of America"
    case uruguay = "Uruguay"
    case uzbekistan = "Uzbekistan"
    case vanuatu = "Vanuatu"
    case venezuela = "Venezuela"
    case vietnam = "Vietnam"
    case yemen = "Yemen"
    case zambia = "Zambia"
    case zimbabwe = "Zimbabwe"
    
    
    var region: Region {
           switch self {
           case .afghanistan, .armenia, .azerbaijan, .bahrain, .bangladesh, .bhutan, .brunei, .cambodia, .china, .india, .indonesia, .iran, .iraq, .israel, .japan, .jordan, .kazakhstan, .kuwait, .kyrgyzstan, .laos, .lebanon, .malaysia, .maldives, .mongolia, .myanmar, .nepal, .northKorea, .oman, .pakistan, .philippines, .qatar, .saudiArabia, .singapore, .southKorea, .sriLanka, .syria, .tajikistan, .thailand, .timorLeste, .turkey, .turkmenistan, .uae, .uzbekistan, .vietnam, .yemen:
               return .asia
           case .albania, .andorra, .austria, .belarus, .belgium, .bosniaAndHerzegovina, .bulgaria, .croatia, .cyprus, .czechia, .denmark, .estonia, .finland, .france, .georgia, .germany, .greece, .hungary, .iceland, .ireland, .italy, .latvia, .liechtenstein, .lithuania, .luxembourg, .malta, .moldova, .monaco, .montenegro, .netherlands, .norway, .poland, .portugal, .romania, .russia, .sanMarino, .serbia, .slovakia, .slovenia, .spain, .sweden, .switzerland, .ukraine, .uk:
               return .europe
           case .algeria, .angola, .benin, .botswana, .burkinaFaso, .burundi, .cameroon, .centralAfricanRepublic, .chad, .comoros, .congo, .coteDIvoire, .democraticRepublicOfTheCongo, .djibouti, .egypt, .equatorialGuinea, .eritrea, .eswatini, .ethiopia, .gabon, .gambia, .ghana, .guinea, .guineaBissau, .kenya, .lesotho, .liberia, .libya, .madagascar, .malawi, .mali, .mauritania, .mauritius, .morocco, .mozambique, .namibia, .niger, .nigeria, .rwanda, .saoTomeAndPrincipe, .senegal, .seychelles, .sierraLeone, .somalia, .southAfrica, .southSudan, .sudan, .tanzania, .togo, .tunisia, .uganda, .zambia, .zimbabwe:
               return .africa
           case .antiguaAndBarbuda, .bahamas, .barbados, .belize, .canada, .costaRica, .cuba, .dominica, .dominicanRepublic, .elSalvador, .grenada, .guatemala, .haiti, .honduras, .jamaica, .mexico, .nicaragua, .panama, .saintKittsAndNevis, .saintLucia, .saintVincentAndTheGrenadines, .trinidadAndTobago, .us:
               return .northAmerica
           case .argentina, .bolivia, .brazil, .chile, .colombia, .ecuador, .guyana, .paraguay, .peru, .suriname, .uruguay, .venezuela:
               return .southAmerica
           case .australia, .fiji, .kiribati, .marshallIslands, .micronesia, .nauru, .newZealand, .palau, .papuaNewGuinea, .samoa, .solomonIslands, .tonga, .tuvalu, .vanuatu:
               return .oceania
           default:
               return .others
           }
       }
}
